"""Add profile_image

Revision ID: 0d5f8f03ebc7
Revises: 221e68f8c1ae
Create Date: 2024-09-27 13:57:19.811147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5f8f03ebc7'
down_revision = '221e68f8c1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
