"""Fix database schema

Revision ID: 87f423009a72
Revises: 7ff86cc83b6f
Create Date: 2024-12-25 17:27:26.223757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '87f423009a72'
down_revision = '7ff86cc83b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_model')
    op.drop_table('class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('class_group', sa.INTEGER(), nullable=False),
    sa.Column('class_code', sa.VARCHAR(length=100), nullable=False),
    sa.Column('class_schedule', sa.VARCHAR(length=100), nullable=False),
    sa.Column('student_list', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('class_group', sa.INTEGER(), nullable=False),
    sa.Column('class_code', sa.VARCHAR(length=100), nullable=False),
    sa.Column('class_schedule', sa.VARCHAR(length=100), nullable=False),
    sa.Column('student_list', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
